apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-volume-prometheus-for-amp-server-0
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 8Gi